# ========================================================================
# App Engine Configuration.
# Full reference is available at:
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
# ========================================================================

runtime: java
env: flex
runtime_config:
  jdk: openjdk8
instance_class: F4
service: default
resources:
  memory_gb: 4
entrypoint: java -noverify -jar lendingbook-0.0.1-SNAPSHOT.war
handlers:
- url: /(.*)
  script: auto
  secure: always
automatic_scaling:
  min_instances: 0
  max_instances: 0
env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  CLOUDSQL_CONNECTION_NAME: lending-book:us-central1:lending-book-db
  # Replace username and password if you aren't using the root user.
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: jpjgml
